
let EoS_iq_skills = [
	"NONE",
	"TYPE_ADVANTAGE_MASTER",
	"ITEM_CATCHER",
	"COURSE_CHECKER",
	"SURE_HIT_ATTACKER",
	"QUICK_DODGER",
	"PP_CHECKER",
	"NONTRAITOR",
	"STATUS_CHECKER",
	"EXP_GO_GETTER",
	"EFFICIENCY_EXPERT",
	"WEAK_TYPE_PICKER",
	"ALL_TERRAIN_HIKER",
	"ABSOLUTE_MOVER",
	"TRAP_AVOIDER",
	"HOUSE_AVOIDER",
	"ENERGY_SAVER",
	"NONSLEEPER",
	"SELF_CURER",
	"TRAP_SEER",
	"LAVA_EVADER",
	"DEDICATED_TRAVELER",
	"ITEM_MASTER",
	"EXCLUSIVE_MOVE_USER",
	"ESCAPIST",
	"LOCK_PICKER",
	"STAIR_SENSOR",
	"COIN_WATCHER",
	"EXP_ELITE",
	"SHARPSHOOTER",
	"FAST_FRIEND",
	"PP_SAVER",
	"BODYGUARD",
	"CAUTIOUS_CREEPER",
	"AGGRESSOR",
	"DEFENDER",
	"INTIMIDATOR",
	"SURVIVALIST",
	"TRAP_BUSTER",
	"COUNTER_HITTER",
	"EXTRA_STRIKER",
	"HIT_AND_RUNNER",
	"PARRY_EXPERT",
	"QUICK_STRIKER",
	"NO_CHARGER",
	"WARY_FIGHTER",
	"GAP_PROBER",
	"POWER_PITCHER",
	"CONCENTRATOR",
	"COUNTER_BASHER",
	"CHEERLEADER",
	"NATURE_GIFTER",
	"WISE_HEALER",
	"QUICK_HEALER",
	"ACUTE_SNIFFER",
	"DEEP_BREATHER",
	"BRICK_TOUGH",
	"MULTITALENT",
	"TIME_TRIPPER",
	"ERRATIC_PLAYER",
	"PRACTICE_SWINGER",
	"NO_DEFEATIST",
	"HAGGLER",
	"CLUTCH_PERFORMER",
	"CRITICAL_DODGER",
	"MAP_SURVEYOR",
	"PIERCE_HURLER",
	"COLLECTOR",
	"TRUE_POWERIST"
];


let EoS_tips = [
	"HEAD_TO_STAIRWAY", //0x00
	"YOU_CAN_CARRY_AND_FIND_ITEMS", //0x01
	"WONDER_TILE", //0x02
	"CHECK_QUICK_HINT", //0x03
	"HELD_ITEM_TRESURE_BAG", //0x04
	"EAT_APPLE_GUMMI_WHEN_HUNGRY", //0x05
	"EXPERIENCE_POINTS", //0x06
	"USE_MOVES_TO_GET_MORE_EXPERIENCE", //0x07
	"HP_LOW_FAINTING", //0x08
	"IQ_SKILLS_AND_TACTICS", //0x09
	"EAT_APPLE_GUMMI_TO_FILL_BELLY", //0x0A
	"ORAN_BERRY_HEALS_HP", //0x0B
	"CHERI_BERRY_CURES_PARALYSIS", //0x0C
	"BLAST_SEED_BREATH_FIRE", //0x0D
	"GEO_PEPPLES_AND_STICKS", //0x0E
	"PECHA_BERRY_CURES_POISION", //0x0F
	"THROW_SLEEP_SEED", //0x10
	"POKE_IS_THIS_WORLDS_MONEY", //0x11
	"MAX_ELIXIER_RESTORES_POWER_POINTS", //0x12
	"HEAL_SEED_CURES_STATUS_CONDITIONS", //0x13
	"STUN_SEED_STUNS", //0x14
	"WARP_SEED_WARPS", //0x15
	"VILE_SEED_REDUCES_DEFENCE_AND_SPECIAL_DEFENCE", //0x16
	"X_EYE_SEED_MAKES_DIZZY", //0x17
	"VIOLENT_SEED_RAISES_ATTACK_AND_SPECIAL_ATTACK", //0x18
	"LOOKALIKE_ITEMS", //0x19
	"WEATHER_ORBS", //0x1A
	"UNUSED0", //0x1B
	"UNUSED1", //0x1C
	"UNUSED2", //0x1D
	"UNUSED3", //0x1E
	"UNUSED4" //0x1F
];


let Eos_ArrayNames = { "eos_iq_skills": EoS_iq_skills, "eos_tips": EoS_tips  };

export function EoS_GetArrayNames(name)
{
	if(Eos_ArrayNames[name])
	{
		return Eos_ArrayNames[name];
	}
	else
	{
		return null;
	}
}

